# To see this module in action use 'make -R run_screen', then type something
# line '0 return' to get the prompt loop to give you a prompt.

# Note that it is possible to use a single two-way stream, and to avoid having
# to blind-type.  See the example in the uart module for details.

include run_screen.mk

include generic.mk
