# Hook up LEDs to PORTD.5 and PORTD.6 (to ground, preferable with some current
# limiting resistors), program wht chip and watch the cross-fade :)  Note that
# the cross-fade looks a little weird with most LEDs since their perceived
# optical output isn't very linear with PWM duty cycle.

include generic.mk
