# To see this module in action, program the chip ('make -rR writeflash')
# then run 'make -rR run_screen' from a terminal to run the screen program
# and see the chip talk to the computer over the serial line.

include run_screen.mk

include generic.mk
