# To see this module in action, program the chip (make -R writeflash) then run
# 'make -R run_screen' from a terminal to run the screen program and see the
# chip talk to the computer over the serial line.

include run_screen.mk

include generic.mk
