COMPILER_MCU = atmega328p
PROGRAMMER_MCU = m328p
CPU_FREQ_DEFINE = -DF_CPU=16000000

PROGNAME = simple_blink
OBJS = simple_blink.o
HEADERS = $(wildcard *.h)

UPLOAD_METHOD = AVRISPmkII_no_bl

include generic.mk
