$(error FIXME: tweak instructions)
# To see this module in action:
#
# 1.  Connect a pushbutton switch from PORTD.2 to ground.
#
# 2.  Program the chip ('make -R writeflash').
#
# 3.  Wait a few seconds for the bootloader to get done after the AVR reboots.
#
# 4.  Run 'make -R run_screen' from a terminal.
#
# 5.  The AVR will echo back next characters in example 5.  Led L on the
#     arduino will toggle on and off (or not) as character are typed depending
#     on whether the button is down as they are typed.
include run_screen.mk

include generic.mk
