# To see this module in action:
#
# 1.  Program the chip ('make -R writeflash').
#
# 2.  Wait a few seconds for the bootloader to get done after the AVR reboots.
#
# 3.  Run 'make -R run_screen' from a terminal.
#
# 4.  You will be prompted to read/write/erase strings from the EEPROM.

include run_screen.mk

include generic.mk
