# To see this module in action, program the chip (make -R writeflash).  Wait a
# few seconds for the bootloader to get done after the AVR reboots.  Then run
# 'make -R run_screen' from a terminal to run the screen program.  Type a
# character and the AVR will send the next character (in the alphanumeric
# sense) back to you.

include run_screen.mk

include generic.mk
