# To see this module in action, program the chip ('make -rR writeflash')
# then run 'make -rR run_screen' from a terminal to run the screen program
# to talk to the chip over the serial line.  There is only one demo command:
# 'u some_string', which just echos the string back.

include run_screen.mk

include generic.mk
